import requests
import pandas as pd
import io
import streamlit as st

NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS",
    "BHARTIARTL.NS", "ICICIBANK.NS", "INFY.NS",
    "SBIN.NS", "HINDUNILVR.NS", "ITC.NS", "LT.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "MARUTI.NS",
    "ASIANPAINT.NS", "SUNPHARMA.NS", "TITAN.NS",
    "BAJFINANCE.NS", "NESTLEIND.NS", "TECHM.NS",
    "HCLTECH.NS", "ULTRACEMCO.NS", "POWERGRID.NS",
    "NTPC.NS", "ONGC.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "JSWSTEEL.NS", "ADANIENT.NS",
    "ADANIPORTS.NS", "COALINDIA.NS", "DRREDDY.NS",
    "CIPLA.NS", "DIVISLAB.NS", "BAJAJFINSV.NS",
    "BAJAJ-AUTO.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "BRITANNIA.NS", "WIPRO.NS", "GRASIM.NS",
    "APOLLOHOSP.NS", "BPCL.NS", "TATACONSUM.NS",
    "HINDALCO.NS", "INDUSINDBK.NS", "SHRIRAMFIN.NS",
    "M&M.NS", "SBILIFE.NS", "HDFCLIFE.NS",
    "ICICIGI.NS"
]

NIFTY_NEXT_50 = [
    "DABUR.NS", "MARICO.NS", "PIDILITIND.NS",
    "HAVELLS.NS", "VOLTAS.NS", "INDIGO.NS",
    "IRCTC.NS", "ZOMATO.NS", "DMART.NS", "TRENT.NS",
    "PERSISTENT.NS", "MPHASIS.NS", "LTIM.NS",
    "COFORGE.NS", "COLPAL.NS", "BERGEPAINT.NS",
    "GODREJCP.NS", "JUBLFOOD.NS", "TORNTPHARM.NS",
    "ALKEM.NS", "LUPIN.NS", "BIOCON.NS",
    "ADANIGREEN.NS", "CANBK.NS", "PNB.NS",
    "BANKBARODA.NS", "FEDERALBNK.NS",
    "IDFCFIRSTB.NS", "CHOLAFIN.NS", "MUTHOOTFIN.NS",
    "LICI.NS", "ICICIPRULI.NS", "SBICARD.NS",
    "SAIL.NS", "NMDC.NS", "GAIL.NS", "IOC.NS",
    "PETRONET.NS", "IGL.NS", "MGL.NS", "AUBANK.NS",
    "BANDHANBNK.NS", "ABCAPITAL.NS", "DIXON.NS",
    "CGPOWER.NS", "BEL.NS", "CONCOR.NS",
    "CRISIL.NS", "PIIND.NS", "MCDOWELL-N.NS"
]

NIFTY_MIDCAP_150 = [
    "ABFRL.NS", "ACC.NS", "AIAENG.NS",
    "AJANTPHARM.NS", "APLLTD.NS", "APOLLOTYRE.NS",
    "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS",
    "BALKRISIND.NS", "BATAINDIA.NS", "BHARATFORG.NS",
    "BHEL.NS", "BRIGADE.NS", "BSE.NS",
    "CAMS.NS", "CANFINHOME.NS", "CEATLTD.NS",
    "CROMPTON.NS", "CYIENT.NS", "DELHIVERY.NS",
    "DEEPAKNTR.NS", "EMAMILTD.NS", "ENDURANCE.NS",
    "ESCORTS.NS", "EXIDEIND.NS", "FORTIS.NS",
    "GLENMARK.NS", "GODREJPROP.NS", "GRANULES.NS",
    "GSPL.NS", "HAPPSTMNDS.NS", "HINDPETRO.NS",
    "IDBI.NS", "INDIANB.NS", "INDHOTEL.NS",
    "INDUSTOWER.NS", "JKCEMENT.NS", "JUBLPHARMA.NS",
    "KAJARIACER.NS", "KANSAINER.NS",
    "KARURVYSYA.NS", "KEC.NS", "KPITTECH.NS",
    "LAURUSLABS.NS", "LICHSGFIN.NS", "LTTS.NS",
    "METROPOLIS.NS", "MOTILALOFS.NS",
    "NATCOPHARM.NS", "NAUKRI.NS", "OBEROIRLTY.NS",
    "OFSS.NS", "PAGEIND.NS", "POLYCAB.NS",
    "TATACOMM.NS", "IDEA.NS", "RAILTEL.NS",
    "RVNL.NS", "SUNDARMFIN.NS", "SUPREMEIND.NS",
    "SYNGENE.NS", "TATAELXSI.NS", "TORNTPOWER.NS",
    "TRIDENT.NS", "TTKPRESTIG.NS", "UBLLTD.NS",
    "UNIONBANK.NS", "VBL.NS", "VEDL.NS",
    "WHIRLPOOL.NS", "WIPRO.NS", "YESBANK.NS",
    "ZEEL.NS", "ZYDUSLIFE.NS", "IRFC.NS",
    "IREDA.NS", "PFC.NS", "RECLTD.NS",
    "NHPC.NS", "SJVN.NS", "MOIL.NS",
    "NATIONALUM.NS", "HINDCOPPER.NS",
    "GMRINFRA.NS", "IRB.NS", "NHAI.NS",
    "APLAPOLLO.NS", "JINDALSAW.NS", "RATNAMANI.NS",
    "RAMCOCEM.NS", "HEIDELBERG.NS", "ORIENTCEM.NS",
    "NUVOCO.NS", "JKPAPER.NS", "WESTPAPER.NS",
    "NAVINFLUOR.NS", "AARTI.NS", "ATUL.NS",
    "CLEAN.NS", "FINEORG.NS", "GALAXYSURF.NS",
    "SUDARSCHEM.NS", "VINATIORGA.NS", "BASF.NS",
    "NOCIL.NS", "PCBL.NS", "BALRAMCHIN.NS",
    "DWARIKESH.NS", "RENUKA.NS", "DBCORP.NS",
    "JAGRAN.NS", "TVTODAY.NS", "ZENSARTECH.NS",
    "HEXAWARE.NS", "MASTEK.NS", "NIITTECH.NS",
    "RATEGAIN.NS", "NETWEB.NS", "TANLA.NS",
    "ROUTE.NS", "MEDPLUS.NS", "VIJAYABANK.NS",
    "SOUTHBANK.NS", "DCBBANK.NS", "RBLBANK.NS",
    "IDFC.NS", "UJJIVANSFB.NS", "EQUITASBNK.NS",
    "SURYODAY.NS", "CREDITACC.NS", "SPANDANA.NS",
    "UTIAMC.NS", "NIFTYIETF.NS", "SUNDARMFIN.NS",
    "MANAPPURAM.NS", "AAVAS.NS", "HOMEFIRST.NS",
    "APTUS.NS", "ANGELONE.NS", "CDSL.NS",
    "MCX.NS", "NSE.NS", "5PAISA.NS",
    "SYMPHONY.NS", "RELAXO.NS", "VGUARD.NS",
    "BLUESTAR.NS", "AMBER.NS", "POLYPLEX.NS",
    "UFLEX.NS", "MOLD-TEK.NS", "TIMETECHNO.NS",
    "LAXMIMACH.NS", "GRINDWELL.NS", "ELGIEQUIP.NS",
    "KFINTECH.NS", "COMPUTER.NS"
]

NIFTY_SMALLCAP_SELECT = [
    "ABSLAMC.NS", "AFFLE.NS", "ALKYLAMINE.NS",
    "ALEMBICLTD.NS", "ALKEM.NS", "AMARAJABAT.NS",
    "AMBUJACEM.NS", "ANANTRAJ.NS", "ANURAS.NS",
    "ARVINDFASN.NS", "ASAHIINDIA.NS", "ASHIANA.NS",
    "BAJAJCON.NS", "BAJAJHLDNG.NS", "BALAJI-TELE.NS",
    "BBTC.NS", "BEML.NS", "BORORENEW.NS",
    "CAMPUS.NS", "CANFINHOME.NS", "CAPLIPOINT.NS",
    "CARTRADE.NS", "CASTROLIND.NS", "CCL.NS",
    "CERA.NS", "CESC.NS", "CHALET.NS",
    "CHOLAHLDNG.NS", "COCHINSHIP.NS", "CSBBANK.NS",
    "DATAMATICS.NS", "DBREALTY.NS", "DCM.NS",
    "DCMSHRIRAM.NS", "DHANUKA.NS", "DHANI.NS",
    "ECLERX.NS", "EIDPARRY.NS", "EKC.NS",
    "ELECTCAST.NS", "ELIN.NS", "EMCURE.NS",
    "EPIGRAL.NS", "ESABINDIA.NS", "ESSEL.NS",
    "FLAIR.NS", "GAEL.NS", "GABRIEL.NS",
    "GARFIBRES.NS", "GLS.NS", "GMDCLTD.NS",
    "GNFC.NS", "GODREJIND.NS", "GOPALSNACKS.NS",
    "GPPL.NS", "GRAVITA.NS", "GREENPANEL.NS",
    "GRSE.NS", "GUJALKALI.NS", "GUJGASLTD.NS",
    "GULFOILLUB.NS", "HAPPYFRG.NS", "HARDWYN.NS",
    "HERANBA.NS", "HFCL.NS", "HIKAL.NS",
    "HINDWAREAP.NS", "HLEGLAS.NS", "HOMEFIRST.NS",
    "HTMEDIA.NS", "HEG.NS", "IBREALEST.NS",
    "IDFCFIRSTB.NS", "IIFL.NS", "IMAGICAA.NS",
    "INDIACEM.NS", "INDIAMART.NS", "INDIGOPNTS.NS",
    "INDOSTAR.NS", "INTELLECT.NS", "IONEXCHANG.NS",
    "ISEC.NS", "ITDCEM.NS", "JAIBALAJI.NS",
    "JBCHEPHARM.NS", "JINDALST.NS", "JMFINANCIL.NS",
    "JSWENERGY.NS", "JTLIND.NS", "JUBLINDS.NS",
    "JYOTHYLAB.NS", "KALYANKJIL.NS", "KAMDHENU.NS",
    "KANSAINER.NS", "KAYNES.NS", "KESORAMIND.NS",
    "KINETIC.NS", "KMCHIL.NS", "KNRCON.NS",
    "KOPRAN.NS", "KOTAKPSU.NS", "KRSNAA.NS",
    "KSCL.NS", "KTKBANK.NS", "LAKSHVILAS.NS",
    "LATENTVIEW.NS", "LAXMIMACH.NS", "LEMONTREE.NS",
    "LGBBROSLTD.NS", "LINC.NS", "LLOYDSENGG.NS",
    "LUMAXTECH.NS", "LUXIND.NS", "MAHSEAMLES.NS",
    "MAITHANALL.NS", "MAPMYINDIA.NS", "MBAPL.NS",
    "MEDANTA.NS", "MEGH.NS", "METROBRAND.NS",
    "MFSL.NS", "MGEL.NS", "MIDHANI.NS",
    "MINDA.NS", "MINDAIND.NS", "MIRZAINT.NS",
    "MMFL.NS", "MNRE.NS", "MOLDTKPAC.NS",
    "MPIL.NS", "MRPL.NS", "MSTCLTD.NS",
    "MTARTECH.NS", "MUTHOOTMF.NS", "NARAYANA.NS",
    "NAVNETEDUL.NS", "NESCO.NS", "NEULANDLAB.NS",
    "NEWGEN.NS", "NIITLTD.NS", "NLCINDIA.NS",
    "NRBBEARING.NS", "NSLNISP.NS", "NUCLEUS.NS",
    "OAL.NS", "OLAELEC.NS", "OLECTRA.NS",
    "OMINFRAL.NS", "ONEPOINT.NS", "OPTOCIRCUI.NS",
    "ORISSAMINE.NS", "PATELENG.NS", "PATINTLOG.NS",
    "PDSL.NS", "PENIND.NS", "PGINVIT.NS",
    "PHOENIX.NS", "PNBHOUSING.NS", "PNCINFRA.NS",
    "POLYMED.NS", "PREMIEREXP.NS", "PRINCEPIPE.NS",
    "PRIVISCL.NS", "PSPPROJECT.NS", "PVRINOX.NS",
    "RAMCOIND.NS", "RANE.NS", "RANEENGINE.NS",
    "RATEGAIN.NS", "RATNAMANI.NS", "RCF.NS",
    "RESPONIND.NS", "RFCL.NS", "RITES.NS",
    "ROLCON.NS", "ROSSARI.NS", "RPG.NS",
    "RPOWER.NS", "RSWM.NS", "SAFARI.NS",
    "SAGCEM.NS", "SAREGAMA.NS", "SBCL.NS",
    "SBICARD.NS", "SCENERY.NS", "SEQUENT.NS",
    "SHARDACROP.NS", "SHAREINDIA.NS", "SHREECEM.NS",
    "SHRIRAMCIT.NS", "SICAL.NS", "SIEMENS.NS",
    "SKIPPER.NS", "SMLISUZU.NS", "SNOWMAN.NS",
    "SOLARA.NS", "SPIC.NS", "SPORTKING.NS",
    "SRPL.NS", "STLTECH.NS", "STYLAMIND.NS",
    "SUDARSCHEM.NS", "SUMICHEM.NS", "SUVEN.NS",
    "SUVENPHAR.NS", "SWSOLAR.NS", "SYMPHONY.NS",
    "TANLA.NS", "TATACOFFEE.NS", "TATAINVEST.NS",
    "TEXRAIL.NS", "THANGAMAYL.NS", "THYROCARE.NS",
    "TIJARIA.NS", "TIINDIA.NS", "TITAGARH.NS",
    "TMVL.NS", "TNPL.NS", "TORENT.NS",
    "TRIVENI.NS", "TTKPRESTIG.NS", "TUBE.NS",
    "TVSSRICHAK.NS", "UCOBANK.NS", "UGROCAP.NS",
    "UJJIVAN.NS", "UNOMINDA.NS", "UTIAMC.NS",
    "VGUARD.NS", "VINATIORGA.NS", "VLSFINANCE.NS",
    "VSTIND.NS", "WABCOINDIA.NS", "WELENT.NS",
    "WELSPUNIND.NS", "WESTLIFE.NS", "WONDERLA.NS",
    "XCHANGING.NS", "YASHO.NS", "YESBANK.NS",
    "ZEEL.NS", "ZENTEC.NS", "ZODIACLOTH.NS",
    "ZOMATO.NS", "ZUARI.NS", "ZYDUSLIFE.NS"
]

COMMODITIES = {
    "Gold": "GC=F",
    "Silver": "SI=F",
    "Crude Oil": "CL=F",
    "Natural Gas": "NG=F",
    "Copper": "HG=F"
}

ALL_STOCKS = list(dict.fromkeys(
    NIFTY_50 + NIFTY_NEXT_50 +
    NIFTY_MIDCAP_150 + NIFTY_SMALLCAP_SELECT
))

COMMODITY_TICKERS = list(COMMODITIES.values())
ALL_INSTRUMENTS = ALL_STOCKS + COMMODITY_TICKERS

SECTOR_MAP = {
    "Banking": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS",
        "KOTAKBANK.NS", "AXISBANK.NS",
        "INDUSINDBK.NS", "FEDERALBNK.NS",
        "BANKBARODA.NS", "CANBK.NS", "PNB.NS",
        "IDFCFIRSTB.NS", "AUBANK.NS",
        "BANDHANBNK.NS", "INDIANB.NS", "IDBI.NS",
        "KARURVYSYA.NS", "RBLBANK.NS",
        "DCBBANK.NS", "CSBBANK.NS", "UJJIVANSFB.NS",
        "EQUITASBNK.NS", "SOUTHBANK.NS",
        "KTKBANK.NS", "LAKSHVILAS.NS",
        "UNIONBANK.NS", "YESBANK.NS", "UCOBANK.NS"
    ],
    "IT": [
        "TCS.NS", "INFY.NS", "HCLTECH.NS",
        "WIPRO.NS", "TECHM.NS", "LTIM.NS",
        "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS",
        "CYIENT.NS", "KPITTECH.NS", "HAPPSTMNDS.NS",
        "LTTS.NS", "OFSS.NS", "NAUKRI.NS",
        "HEXAWARE.NS", "MASTEK.NS", "NIITTECH.NS",
        "RATEGAIN.NS", "TANLA.NS", "ROUTE.NS",
        "INTELLECT.NS", "NEWGEN.NS", "NUCLEUS.NS",
        "DATAMATICS.NS", "ECLERX.NS", "ZENSARTECH.NS",
        "LATENTVIEW.NS"
    ],
    "Auto": [
        "MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS",
        "HEROMOTOCO.NS", "EICHERMOT.NS", "M&M.NS",
        "ASHOKLEY.NS", "ESCORTS.NS", "BALKRISIND.NS",
        "BHARATFORG.NS", "ENDURANCE.NS", "CEATLTD.NS",
        "EXIDEIND.NS", "SMLISUZU.NS", "TVSMOTOR.NS",
        "SUPRAJIT.NS", "MINDAIND.NS", "MINDA.NS",
        "GABRIEL.NS", "LUMAXTECH.NS", "RANE.NS",
        "RANEENGINE.NS", "UNOMINDA.NS", "TVSSRICHAK.NS"
    ],
    "Pharma": [
        "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS",
        "DIVISLAB.NS", "LUPIN.NS", "AUROPHARMA.NS",
        "ALKEM.NS", "TORNTPHARM.NS", "BIOCON.NS",
        "NATCOPHARM.NS", "JUBLPHARMA.NS",
        "GRANULES.NS", "LAURUSLABS.NS",
        "METROPOLIS.NS", "GLENMARK.NS", "AJANTPHARM.NS",
        "CAPLIPOINT.NS", "ZYDUSLIFE.NS",
        "SUVENPHAR.NS", "SOLARA.NS", "EMCURE.NS",
        "NEULANDLAB.NS", "JBCHEPHARM.NS",
        "SEQUENT.NS", "THYROCARE.NS", "KRSNAA.NS"
    ],
    "FMCG": [
        "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS",
        "BRITANNIA.NS", "DABUR.NS", "MARICO.NS",
        "COLPAL.NS", "GODREJCP.NS", "EMAMILTD.NS",
        "TATACONSUM.NS", "JUBLFOOD.NS",
        "MCDOWELL-N.NS", "VBL.NS", "BALRAMCHIN.NS",
        "DWARIKESH.NS", "RENUKA.NS", "EIDPARRY.NS",
        "WESTLIFE.NS", "GOPALSNACKS.NS"
    ],
    "Energy": [
        "RELIANCE.NS", "ONGC.NS", "BPCL.NS",
        "IOC.NS", "GAIL.NS", "PETRONET.NS",
        "ADANIGREEN.NS", "NTPC.NS", "POWERGRID.NS",
        "HINDPETRO.NS", "GSPL.NS", "IGL.NS",
        "MGL.NS", "COALINDIA.NS", "NHPC.NS",
        "SJVN.NS", "JSWENERGY.NS", "TORNTPOWER.NS",
        "CESC.NS", "MRPL.NS", "NLCINDIA.NS",
        "IREDA.NS", "SWSOLAR.NS", "RPOWER.NS"
    ],
    "Metals": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS",
        "SAIL.NS", "NMDC.NS", "VEDL.NS",
        "NATIONALUM.NS", "HINDCOPPER.NS",
        "MOIL.NS", "RATNAMANI.NS", "APLAPOLLO.NS",
        "JINDALSAW.NS", "JINDALST.NS", "JTLIND.NS",
        "JAIBALAJI.NS", "ELECTCAST.NS", "NSLNISP.NS",
        "WELSPUNIND.NS", "SKIPPER.NS", "UCOBANK.NS",
        "GMDC.NS", "GMDCLTD.NS"
    ],
    "Finance": [
        "BAJFINANCE.NS", "BAJAJFINSV.NS",
        "CHOLAFIN.NS", "MUTHOOTFIN.NS",
        "SBICARD.NS", "ABCAPITAL.NS",
        "CANFINHOME.NS", "LICHSGFIN.NS",
        "MOTILALOFS.NS", "CRISIL.NS", "LICI.NS",
        "SBILIFE.NS", "HDFCLIFE.NS", "ICICIGI.NS",
        "ICICIPRULI.NS", "SHRIRAMFIN.NS",
        "MANAPPURAM.NS", "AAVAS.NS", "HOMEFIRST.NS",
        "APTUS.NS", "ANGELONE.NS", "ISEC.NS",
        "JMFINANCIL.NS", "IIFL.NS", "5PAISA.NS",
        "CREDITACC.NS", "SPANDANA.NS", "MFSL.NS",
        "PNBHOUSING.NS", "INDOSTAR.NS",
        "CHOLAHLDNG.NS", "DHANI.NS", "MMFL.NS",
        "VLSFINANCE.NS", "UJJIVAN.NS", "IDFC.NS",
        "KFINTECH.NS", "CAMS.NS", "CDSL.NS",
        "MCX.NS", "UTIAMC.NS"
    ],
    "Consumer": [
        "TITAN.NS", "ASIANPAINT.NS", "PIDILITIND.NS",
        "HAVELLS.NS", "CROMPTON.NS", "DIXON.NS",
        "VOLTAS.NS", "BATAINDIA.NS", "BERGEPAINT.NS",
        "KANSAINER.NS", "KAJARIACER.NS", "PAGEIND.NS",
        "POLYCAB.NS", "ASTRAL.NS", "VGUARD.NS",
        "SYMPHONY.NS", "RELAXO.NS", "BLUESTAR.NS",
        "AMBER.NS", "CERA.NS", "HINDWAREAP.NS",
        "METROBRAND.NS", "SAFARI.NS", "CAMPUS.NS",
        "KALYANKJIL.NS", "TTKPRESTIG.NS", "LUXIND.NS"
    ],
    "Infra": [
        "LT.NS", "ADANIPORTS.NS", "ADANIENT.NS",
        "ULTRACEMCO.NS", "GRASIM.NS", "CONCOR.NS",
        "BEL.NS", "BHEL.NS", "CGPOWER.NS",
        "KEC.NS", "INDUSTOWER.NS", "JKCEMENT.NS",
        "RVNL.NS", "RAILTEL.NS", "IRFC.NS",
        "GRSE.NS", "MIDHANI.NS", "COCHINSHIP.NS",
        "BEML.NS", "TITAGARH.NS", "KNRCON.NS",
        "PSPPROJECT.NS", "PNCINFRA.NS", "ITDCEM.NS",
        "IRB.NS", "GMRINFRA.NS", "PATELENG.NS",
        "GPPL.NS", "DBREALTY.NS", "BRIGADE.NS",
        "ANANTRAJ.NS", "IBREALEST.NS",
        "GODREJPROP.NS", "OBEROIRLTY.NS",
        "CHALET.NS", "LEMONTREE.NS",
        "PHEONIX.NS", "NESCO.NS", "RAMCOCEM.NS",
        "HEIDELBERG.NS", "ORIENTCEM.NS"
    ],
    "Telecom": [
        "BHARTIARTL.NS", "TATACOMM.NS",
        "IDEA.NS", "RAILTEL.NS", "STLTECH.NS",
        "HFCL.NS", "ROUTE.NS"
    ],
    "Healthcare": [
        "APOLLOHOSP.NS", "FORTIS.NS",
        "NARAYANA.NS", "MEDANTA.NS",
        "SYNGENE.NS", "METROPOLIS.NS",
        "KRSNAA.NS", "THYROCARE.NS", "MEDPLUS.NS"
    ],
    "Chemicals": [
        "DEEPAKNTR.NS", "AARTI.NS", "ATUL.NS",
        "NAVINFLUOR.NS", "CLEAN.NS", "FINEORG.NS",
        "GALAXYSURF.NS", "SUDARSCHEM.NS",
        "VINATIORGA.NS", "NOCIL.NS", "PCBL.NS",
        "ALKYLAMINE.NS", "BASF.NS", "GNFC.NS",
        "GUJALKALI.NS", "EPIGRAL.NS", "ROSSARI.NS",
        "HERANBA.NS", "SHARDACROP.NS", "DHANUKA.NS",
        "SUMICHEM.NS", "SUVEN.NS"
    ]
}

SECTOR_INDICES = {
    "Banking": "^NSEBANK",
    "IT": "^CNXIT",
    "Auto": "^CNXAUTO",
    "Pharma": "^CNXPHARMA",
    "FMCG": "^CNXFMCG",
    "Energy": "^CNXENERGY",
    "Metals": "^CNXMETAL",
    "Finance": "^CNXFINANCE",
    "Consumer": "^CNXCONSUMER",
    "Infra": "^CNXINFRA",
    "Telecom": "^CNXTELECOM"
}

NIFTY_INDEX = "^NSEI"

@st.cache_data(ttl=86400)
def get_nse_all_stocks():
    """
    Fetch complete NSE EQ series stock list.
    Falls back to curated ALL_STOCKS on failure.
    """
    try:
        headers = {
            "User-Agent": "Mozilla/5.0",
            "Accept": "text/csv",
        }
        url = (
            "https://archives.nseindia.com"
            "/content/equities/EQUITY_L.csv"
        )
        resp = requests.get(
            url, headers=headers, timeout=15
        )
        if resp.status_code != 200:
            return ALL_STOCKS
        import io
        df = pd.read_csv(
            io.StringIO(resp.text)
        )
        df.columns = df.columns.str.strip()
        series_col = next(
            (c for c in df.columns
             if "SERIES" in c.upper()), None
        )
        symbol_col = next(
            (c for c in df.columns
             if "SYMBOL" in c.upper()), None
        )
        if not symbol_col:
            return ALL_STOCKS
        if series_col:
            df = df[
                df[series_col].str.strip() == "EQ"
            ]
        symbols = [
            f"{s.strip()}.NS"
            for s in df[symbol_col].tolist()
            if isinstance(s, str) and s.strip()
        ]
        return list(dict.fromkeys(symbols)) if symbols else ALL_STOCKS
    except Exception:
        return ALL_STOCKS

def get_sector(ticker):
    for sector, tickers in SECTOR_MAP.items():
        if ticker in tickers:
            return sector
    return "Other"

def is_commodity(ticker):
    return ticker in COMMODITY_TICKERS

def get_commodity_name(ticker):
    for name, t in COMMODITIES.items():
        if t == ticker:
            return name
    return ticker