NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "ICICIBANK.NS",
    "INFY.NS", "SBIN.NS", "HINDUNILVR.NS", "ITC.NS", "LT.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "MARUTI.NS", "ASIANPAINT.NS", "SUNPHARMA.NS",
    "TITAN.NS", "BAJFINANCE.NS", "NESTLEIND.NS", "TECHM.NS", "HCLTECH.NS",
    "ULTRACEMCO.NS", "POWERGRID.NS", "NTPC.NS", "ONGC.NS", "TATAMOTORS.NS",
    "TATASTEEL.NS", "JSWSTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS", "COALINDIA.NS",
    "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS", "BAJAJFINSV.NS", "BAJAJ-AUTO.NS",
    "EICHERMOT.NS", "HEROMOTOCO.NS", "BRITANNIA.NS", "WIPRO.NS",
    "GRASIM.NS", "APOLLOHOSP.NS", "BPCL.NS", "TATACONSUM.NS", "HINDALCO.NS",
    "INDUSINDBK.NS", "SHRIRAMFIN.NS", "M&M.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "ICICIGI.NS"
]

NIFTY_NEXT_50 = [
    "DABUR.NS", "MARICO.NS", "PIDILITIND.NS", "HAVELLS.NS", "VOLTAS.NS",
    "INDIGO.NS", "IRCTC.NS", "ZOMATO.NS", "DMART.NS", "TRENT.NS",
    "PERSISTENT.NS", "MPHASIS.NS", "LTIM.NS", "COFORGE.NS", "COLPAL.NS",
    "BERGEPAINT.NS", "GODREJCP.NS", "JUBLFOOD.NS", "TORNTPHARM.NS",
    "ALKEM.NS", "LUPIN.NS", "BIOCON.NS", "ADANIGREEN.NS", "CANBK.NS",
    "PNB.NS", "BANKBARODA.NS", "FEDERALBNK.NS", "IDFCFIRSTB.NS",
    "CHOLAFIN.NS", "MUTHOOTFIN.NS", "LICI.NS", "ICICIPRULI.NS", "SBICARD.NS",
    "SAIL.NS", "NMDC.NS", "GAIL.NS", "IOC.NS", "PETRONET.NS",
    "IGL.NS", "MGL.NS", "AUBANK.NS", "BANDHANBNK.NS", "ABCAPITAL.NS",
    "DIXON.NS", "CGPOWER.NS", "BEL.NS", "CONCOR.NS", "CRISIL.NS",
    "PIIND.NS", "MCDOWELL-N.NS"
]

NIFTY_MIDCAP = [
    "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS", "BALKRISIND.NS",
    "BATAINDIA.NS", "BHARATFORG.NS", "BHEL.NS", "CAMS.NS",
    "CANFINHOME.NS", "CEATLTD.NS", "CROMPTON.NS", "CYIENT.NS",
    "DELHIVERY.NS", "EMAMILTD.NS", "ENDURANCE.NS", "ESCORTS.NS",
    "EXIDEIND.NS", "FORTIS.NS", "GODREJPROP.NS", "GRANULES.NS",
    "GSPL.NS", "HAPPSTMNDS.NS", "HINDPETRO.NS", "HONAUT.NS",
    "IDBI.NS", "INDIANB.NS", "INDHOTEL.NS", "INDUSTOWER.NS",
    "JINDALSAW.NS", "JKCEMENT.NS", "JUBLPHARMA.NS", "KAJARIACER.NS",
    "KANSAINER.NS", "KARURVYSYA.NS", "KEC.NS", "KPITTECH.NS",
    "LAURUSLABS.NS", "LICHSGFIN.NS", "LINDEINDIA.NS", "LTTS.NS",
    "METROPOLIS.NS", "MOTILALOFS.NS", "MPHASIS.NS", "NATCOPHARM.NS",
    "NAUKRI.NS", "OBEROIRLTY.NS", "OFSS.NS", "PAGEIND.NS",
    "POLYCAB.NS", "RAIN.NS"
]

COMMODITIES = {
    "Gold": "GC=F",
    "Silver": "SI=F",
    "Crude Oil": "CL=F",
    "Natural Gas": "NG=F",
    "Copper": "HG=F"
}

ALL_STOCKS = list(dict.fromkeys(NIFTY_50 + NIFTY_NEXT_50 + NIFTY_MIDCAP))
COMMODITY_TICKERS = list(COMMODITIES.values())
ALL_INSTRUMENTS = ALL_STOCKS + COMMODITY_TICKERS

SECTOR_MAP = {
    "Banking": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS",
        "AXISBANK.NS", "INDUSINDBK.NS", "FEDERALBNK.NS", "BANKBARODA.NS",
        "CANBK.NS", "PNB.NS", "IDFCFIRSTB.NS", "AUBANK.NS", "BANDHANBNK.NS"
    ],
    "IT": [
        "TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS",
        "LTIM.NS", "MPHASIS.NS", "PERSISTENT.NS", "COFORGE.NS",
        "CYIENT.NS", "KPITTECH.NS", "HAPPSTMNDS.NS", "LTTS.NS", "OFSS.NS"
    ],
    "Auto": [
        "MARUTI.NS", "TATAMOTORS.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS",
        "EICHERMOT.NS", "M&M.NS", "ASHOKLEY.NS", "ESCORTS.NS",
        "BALKRISIND.NS", "BHARATFORG.NS", "ENDURANCE.NS", "CEATLTD.NS"
    ],
    "Pharma": [
        "SUNPHARMA.NS", "DRREDDY.NS", "CIPLA.NS", "DIVISLAB.NS",
        "LUPIN.NS", "AUROPHARMA.NS", "ALKEM.NS", "TORNTPHARM.NS",
        "BIOCON.NS", "NATCOPHARM.NS", "JUBLPHARMA.NS", "GRANULES.NS",
        "LAURUSLABS.NS", "METROPOLIS.NS"
    ],
    "FMCG": [
        "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS",
        "DABUR.NS", "MARICO.NS", "COLPAL.NS", "GODREJCP.NS",
        "EMAMILTD.NS", "TATACONSUM.NS", "JUBLFOOD.NS", "MCDOWELL-N.NS"
    ],
    "Energy": [
        "RELIANCE.NS", "ONGC.NS", "BPCL.NS", "IOC.NS", "GAIL.NS",
        "PETRONET.NS", "ADANIGREEN.NS", "NTPC.NS", "POWERGRID.NS",
        "HINDPETRO.NS", "GSPL.NS", "IGL.NS", "MGL.NS"
    ],
    "Metals": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS",
        "SAIL.NS", "NMDC.NS", "JINDALSTEL.NS", "JINDALSAW.NS"
    ],
    "Finance": [
        "BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "MUTHOOTFIN.NS",
        "SBICARD.NS", "ABCAPITAL.NS", "CANFINHOME.NS", "LICHSGFIN.NS",
        "MOTILALOFS.NS", "CRISIL.NS", "LICI.NS", "SBILIFE.NS",
        "HDFCLIFE.NS", "ICICIGI.NS", "ICICIPRULI.NS"
    ],
    "Consumer": [
        "TITAN.NS", "ASIANPAINT.NS", "PIDILITIND.NS", "HAVELLS.NS",
        "CROMPTON.NS", "DIXON.NS", "VOLTAS.NS", "BATAINDIA.NS",
        "BERGEPAINT.NS", "KANSAINER.NS", "KAJARIACER.NS", "PAGEIND.NS",
        "POLYCAB.NS"
    ],
    "Infra": [
        "LT.NS", "ADANIPORTS.NS", "ADANIENT.NS", "ULTRACEMCO.NS",
        "GRASIM.NS", "CONCOR.NS", "BEL.NS", "BHEL.NS", "CGPOWER.NS",
        "KEC.NS", "INDUSTOWER.NS", "JKCEMENT.NS"
    ],
    "Healthcare": [
        "APOLLOHOSP.NS", "FORTIS.NS", "LINDEINDIA.NS"
    ],
    "Hospitality": [
        "INDHOTEL.NS", "OBEROIRLTY.NS"
    ],
    "Realty": [
        "GODREJPROP.NS"
    ],
    "Telecom": [
        "BHARTIARTL.NS", "IDEA.NS", "TATACOMM.NS", "INDUSTOWER.NS"
    ],
}

SECTOR_INDICES = {
    "Banking": "^NSEBANK",
    "IT": "^CNXIT",
    "Auto": "^CNXAUTO",
    "Pharma": "^CNXPHARMA",
    "FMCG": "^CNXFMCG",
    "Energy": "^CNXENERGY",
    "Metals": "^CNXMETAL",
    "Finance": "^CNXFINANCE",
    "Consumer": "^CNXCONSUMER",
    "Infra": "^CNXINFRA"
}

NIFTY_INDEX = "^NSEI"

def get_sector(ticker):
    for sector, tickers in SECTOR_MAP.items():
        if ticker in tickers:
            return sector
    return "Other"

def is_commodity(ticker):
    return ticker in COMMODITY_TICKERS

def get_commodity_name(ticker):
    for name, t in COMMODITIES.items():
        if t == ticker:
            return name
    return ticker